name = "Ergo"
description = "A Simple Blog Theme focused on Writing, inspired by svbtle"
license = "MIT"
homepage = "https://github.com/InsidiousMind/Ergo"
min_version = "0.4.1"
demo = "https://ergo.liquidthink.net"

[author]
name = "Andrew Plaza"
homepage = "https://liquidthink.net"
